[project]
name = "loader"
version = "0.1.0"
description = "Loading data from google sheet"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
